### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by nizwiz** [IRSMsoso/dante-control-rs#1]
This library seems to be very useful. However, without a license it cannot really be used in any way. Would you consider endowing this project (and dante-cli as well) with a license of your choice?
Thanks

EDIT: Oh, I just saw that the Cargo.toml file refers to `Apache-2.0`. Still, adding a license to the repo would be a good idea for visibility, I think.

**Comment by IRSMsoso** [comment]
Good idea, done.
